[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["shell", "homebrew"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
pr-run-mode = "skip"

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04"

[dist.homebrew]
tap = "maxwellsdm1867/homebrew-tap"
